import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ApolloWrapper } from "@/lib/graphql/ApolloWrapper";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { cookies } from "next/headers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
			>
				<ApolloWrapper>
					<SidebarProvider>
						<AppSidebar />
						<main>
							<SidebarTrigger />
							{children}
						</main>
						<Toaster
							richColors
							position="top-right"
							duration={3000}
							closeButton
						/>
					</SidebarProvider>
				</ApolloWrapper>
			</body>
		</html>
	);
}
